#!/bin/bash

# Begin downloading a video from youtube and immediately play with mplayer
# To abort download when quitting mplayer remove '--output-error warn'
# See the 'yd' command for deleting the last downloaded video

SPEED=2 # Playback speed
SAVE_PATH=/home/juul/data/youtube/watch # Where to save videos
RESOLUTION=1080 # The best available version in this (vertical) resolution or the closest available lower resolution will be used
SUBTITLES=no # Set this to "yes" if you want to show subtitles during playback. Subtitles will always be downloaded

cd $SAVE_PATH

echo "Downloading description"
OUTPUT=$(youtube-dl --restrict-filenames --skip-download --write-description --write-all-thumbnails --write-auto-sub "$@")

DESCFILE=$(echo "$OUTPUT" | grep -E -o '[^[:blank:]]+\.description$')
echo "Wrote $DESCFILE"

OLDSUBFILE=$(echo "$OUTPUT" | grep -E -o '[^[:blank:]]+\.vtt$')

if [ ! -z "$OLDSUBFILE" ]; then
  # Convert .vtt subtitle to .srt
  SUBFILE=$(echo $OLDSUBFILE | sed 's/\...\.vtt$/\.srt/')
  ffmpeg -i $OLDSUBFILE $SUBFILE
  rm $OLDSUBFILE
fi

# Remember what we watched (even if the yd command is called later)
mkdir -p watched
cp $DESCFILE watched/

VIDFILE=$(echo $DESCFILE | sed 's/\.description$/.mp4/') # We don't actually know the real file format but assume mp4

if [ -f "$VIDFILE" ]; then
  echo "Video already downloaded" >&2
  exit 1
fi

echo "Downloading $VIDFILE"

echo $DESCFILE > ${SAVE_PATH}/latest

FILTER="'(best[height<=${RESOLUTION}])'"

# It appears that VLC does not have a way to disable showing subtitles from the command line. Pressing 'v' will hide them.
CMD="youtube-dl -q -o - -f $FILTER \"$@\" | tee --output-error warn \"$VIDFILE\" | vlc --rate 2.0 --fullscreen"

if [ ! -z $SUBFILE ] && [ "$SUBTITLES" == "yes" ]; then
  CMD="$CMD --sub-file $SUBFILE"
fi

CMD="$CMD -"

eval $CMD

# The `-subfile` option for mplayer is currently broken
# Also increasing playback speed to over 2.0 does not work well
# mplayer -cache 30720 -cache-min 2 -fs -af scaletempo -speed $SPEED -

